export const STATES = {
    "Telangana": {
        "Medchal-Malkajgiri": [
            "Vidya Jyothi Institute of Technology",
            "VNR Vignana Jyothi Institute of Engineering and Technology",
            "CMR College of Engineering & Technology",
            "Institute of Aeronautical Engineering",
            "Malla Reddy College of Engineering and Technology",
            "St. Martin's Engineering College",
            "MLR Institute of Technology",
            "Guru Nanak Institutions Technical Campus",
            "Geethanjali College of Engineering and Technology",
            "Kommuri Pratap Reddy Institute of Technology",
            "ACE Engineering College",
            "CMR Technical Campus",
            "Narasimha Reddy Engineering College",
            "Malla Reddy Engineering College",
            "St. Peter's Engineering College",
            "Nalla Malla Reddy Engineering College"
            // Removed "Medchal" as it's a place name, not a college
        ],
        "Hyderabad": [
            "Chaitanya Bharathi Institute of Technology",
            "Vasavi College of Engineering",
            "MVSR Engineering College",
            "Osmania University",
            "JNTU Hyderabad",
            "International Institute of Information Technology, Hyderabad (IIIT-H)",
            "Muffakham Jah College of Engineering and Technology",
            "Deccan College of Engineering and Technology",
            "Stanley College of Engineering and Technology for Women",
            "Bhojreddy Engineering College for Women",
            "JNTUH College of Engineering Hyderabad",
            "Lords Institute of Engineering and Technology",
            "AAR Mahaveer Engineering College",
            "Abhinav Hi-Tech College of Engineering",
            "Al-Habeeb College of Engineering and Technology",
            "Amina Institute of Technology",
            "Anurag Group of Institutions",
            "Anwarul-Uloom College of Engineering and Technology",
            "Arjun College of Technology and Sciences",
            "Asifia College of Engineering and Technology",
            "Aurobindo Institute of Engineering and Technology",
            "Aurora's Scientific Technological and Research Academy",
            "Aurora's Seethaiah Engineering College",
            "Aurora's Technical and Management Campus",
            "Aurora's Technological and Research Institute",
            "Avanthi's Scientific Technological and Research Academy",
            "Azad College of Engineering and Technology",
            "BITS Pilani- Hyderabad Campus",
            "BVRIT Hyderabad College of Engineering for Women",
            "Bharat Engineering College",
            "Bharat Institute of Engineering and Technology",
            "Bhaskar Engineering College",
            "Brilliant Grammar School Educational Society's Group of Institutions",
            "Brilliant Institute of Engineering and Technology",
            "CVR College of Engineering",
            "Center for Spatial Information Technology",
            "Central Institute of Tool Design",
            "Chilkur Balaji Institute of Technology",
            "DRK College of Engineering and Technology",
            "DRK Institute of Science and Technology",
            "DVR College of Engineering and Technology",
            "Dr VRK Womens College of Engineering and Technology",
            "G Narayanamma Institute of Technology and Science For Women",
            "Geethanjali College of Engineering and Technology",
            "Global Institute of Engineering and Technology",
            "Gokaraju Rangaraju Institute of Engineering and Technology",
            "Government Institute of Electronics",
            "Government Polytechnic",
            "Government Polytechnic for Women Minorities",
            "Guru Nanak Institutions Technical Campus",
            "Hasvita Institute of Engineering and Technology",
            "Hasvita Institute of Management and Technology",
            "Hi-Point College of Engineering and Technology",
            "Holy Mary Institute of Technology",
            "Hyderabad Institute of Technology and Management",
            "ICFAI Foundation for Higher Education",
            "ICFAI Tech School",
            "ISL Engineering College",
            "Indian Institute of Technology Hyderabad",
            "Institute of Science and Technology",
            "International Institute of Information Technology",
            "JB Institute of Engineering and Technology",
            "JNTUH College of Engineering",
            "Jawaharlal Nehru Architecture and Fine Arts University",
            "Jawaharlal Nehru Architecture and Fine Arts University School of Planning and Architecture",
            "Jawaharlal Nehru Technological University",
            "Joginpally B R Engineering College",
            "Keshav Memorial Institute of Technology",
            "Krishna Murthy Institute of Technology and Engineering",
            "Lords Institute of Engineering and Technology",
            "MJ College of Engineering and Technology",
            "MLR Institute of Technology",
            "MVSR Engineering College",
            "Mahatma Gandhi Institute of Technology",
            "Mahaveer Institute of Science and Technology",
            "Maheshwara Engineering College",
            "Mahindra Ecole Centrale",
            "Malla Reddy College of Engineering",
            "Malla Reddy College of Engineering and Technology",
            "Malla Reddy Engineering College",
            "Malla Reddy Engineering College and Management Sciences",
            "Malla Reddy Engineering College for Women",
            "Malla Reddy Institute of Engineering and Technology",
            "Malla Reddy Institute of Technology",
            "Malla Reddy Institute of Technology and Sciences",
            "Marri Laxman Reddy Institute of Technology and Management",
            "Matrusri Engineering College",
            "Maturi Venkata Subba Rao Engineering College",
            "Maulana Azad National Urdu University",
            "Methodist College of Engineering and Technology",
            "Moghal College of Engineering and Technology",
            "Mona College of Engineering and Technology",
            "Muffakham Jah College of Engineering and Technology",
            "Mumtaz College of Engineering and Technology",
            "Nalla Malla Reddy Engineering College",
            "Nalla Narsimha Reddy Education Society's Group of Institutions",
            "Narayana Engineering and Technical Campus",
            "Nawab Shah Alam Khan College of Engineering and Technology",
            "Nizam Institute of Engineering and Technology",
            "Noble College of Engineering and Technology for Women",
            "Patanam Rajender Reddy Memorial Engineering College",
            "Pratnam Rajendar Reddy Memorial College",
            "Princeton College of Engineering and Technology",
            "Priyadarshini Institute of Science and Technology",
            "RRS College of Engineering and Technology",
            "Rajiv Gandhi University of Knowledge Technologies",
            "Ramrao Adik Institute of Technology",
            "Ratnapuri Institute of Technology College of Polytechnic",
            "Royal Institute of Technology and Science",
            "SVS Group of institution",
            "Sagar Institute of Technology",
            "Samskruti College of Engineering and Technology",
            "School of Information Technology",
            "Shadan College of Engineering and Technology",
            "Shadan Women's College of Engineering and Technology",
            "Shahjehan College of Engineering and Technology",
            "Siddhartha Institute of Technology and Sciences",
            "Sidhartha Institute of Engineering and Technology",
            "Sphoorthy Engineering College",
            "Sree Dattha Institute of Engineering and Sciences",
            "Sreenidhi Institute of Science and Technology",
            "Sreyas Institute of Engineering and Technology",
            "Sri Chaitanya Technical Campus",
            "Sri Indu College of Engineering and Technology",
            "Sri Indu Institute of Engineering and Technology",
            "Sridevi Women's Engineering College",
            "St Martin's Engineering College",
            "St Peter's Engineering College",
            "Stanley College of Engineering and Technology for Women",
            "Swami Vivekananda Institute of Technology",
            "Swathi Institute of Technology and Sciences",
            "TKR College of Engineering and Technology",
            "TRR College of Engineering",
            "TRR College of Engineering and Technology",
            "TRR College of Technology",
            "TRR Engineering College",
            "Teegala Krishna Reddy Engineering College",
            "Telangana State Aviation Academy",
            "Tirumala Engineering College",
            "Turbomachinery Institute of Technology and Sciences",
            "University College of Engineering",
            "University of Hyderabad",
            "VIF College of Engineering and Technology",
            "VNR Vignana Jyothi Institute of Engineering and Technology",
            "Vardhaman College of Engineering",
            "Vasavi College of Engineering",
            "Vignana Bharathi Institute of Technology",
            "Vishwa Bharathi College of Engineering",
            "Vishwa Bharathi PG College of Engineering and Management",
            "Visvesvaraya College of Engineering and Technology",
            "Vivekananda Group of Institutions"
        ],
        "Ranga Reddy": [
            "CVR College of Engineering",
            "Mahatma Gandhi Institute of Technology",
            "Gokaraju Rangaraju Institute of Engineering and Technology",
            "Vardhaman College of Engineering",
            "BV Raju Institute of Technology (BVRIT)",
            "CMR Institute of Technology",
            "Sri Indu College of Engineering and Technology",
            "Vignan Institute of Technology and Science",
            "Keshav Memorial Institute of Technology",
            "TKR College of Engineering and Technology",
            "Sphoorthy Engineering College",
            "KG Reddy College of Engineering and Technology",
            "Sreyas Institute of Engineering and Technology",
            "Vidya Jyothi Institute of Technology",
            "Neil Gogte Institute of Technology",
            "Methodist College of Engineering and Technology",
            "Swami Vivekananda Institute of Technology",
            "Anwarul-Uloom College of Engineering and Technology",
            "Farah Engineering College",
            "Farah Institute of Technology",
            "Kasireddy Narayan Reddy College of Engineering and Research",
            "Patnam Rajender Reddy Memorial Engineering College",
            "Pragna Bharath Institute of Technology",
            "Scient Institute of Technology"
        ],
        "Warangal": [
            "Kakatiya Institute of Technology & Science",
            "SR University",
            "Vaagdevi College of Engineering",
            "National Institute of Technology, Warangal (NITW)",
            "SR Engineering College",
            "Vaagdevi Engineering College",
            "Ramappa Engineering College",
            "Jayamukhi Institute of Technological Sciences",
            "Vinuthna Institute of Technology and Science",
            "Chaitanya Institute of Technology and Science",
            "Balaji Institute of Technology & Science",
            "Aarushi Group of Institutions",
            "Aurora's Research and Technological Institute",
            "Balaji Institute of Technology and Science",
            "Christu Jyothi Institute of Technology and Science",
            "Ganapathy College of Engineering",
            "Ganapathy Engineering College",
            "Pulla Reddy Institute of Technology",
            "SVS Polytechnic",
            "Sujala Bharati Institute of Technology",
            "Talla Padmavathi College of Engineering",
            "VMR Polytechnic",
            "Vidya Bharathi Institute of Technology",
            "Warangal Institute of Technology and Science"
        ],
        "Karimnagar": [
            "JNTU Manthani",
            "Jyothishmathi Institute of Technology and Science",
            "Vaageswari College of Engineering",
            "JNTUH College of Engineering",
            "Jyothishmathi Institute of Technological Sciences",
            "Kamala Institute of Technology and Science",
            "Sree Chaitanya College of Engineering",
            "Sree Chaitanya Institute of Technological Sciences",
            "Trinity College of Engineering and Technology",
            "Vaageshwari College of Engineering",
            "Vaageswari Engineering College",
            "Vivekananda Institute of Technology and Science"
        ],
        "Nalgonda": [
            "Mahatma Gandhi University",
            "Nalgonda Institute of Technology and Science",
            "Adusumilli Vijaya Institute of Technology and Research Centre",
            "Anurag Engineering College",
            "Aurora's Engineering College",
            "Khader Memorial College of Engineering and Technology",
            "Mina Institute of Engineering and Technology for Women",
            "Ramanadatirtha Engineering College",
            "Swami Ramananda Tirtha Institute of Science and Technology"
        ],
        "Khammam": [
            "Khammam Institute of Technology & Science",
            "Swaraj India Institute of Technology",
            "Abdulkalam Institute of Technological Sciences",
            "Anubose Institute of Technology",
            "Daripally Anantha Ramulu College of Engineering and Technology",
            "Hasvita Institute of Science and Technology",
            "KLR College of Engineering and Technology",
            "Laqshya Institute of Technology and Sciences",
            "Medha Institute of Science and Technology for Women",
            "Mohammadiya Institute of Technology",
            "Swarna Bharathi Institute of Science and Technology",
            "Vijaya Engineering College"
        ],
        "Sangareddy": [
            "Gitam University",
            "IIT Hyderabad",
            "Anurag Engineering College",
            "TRR College of Engineering",
            "JNTUH College of Engineering",
            "MNR College of Engineering and Technology"
        ],
        "Adilabad": [
            "Rajiv Gandhi University of Knowledge Technologies, Basar"
        ],
        "Nizamabad": [
            "Arkay College of Engineering and Technology",
            "Kakatiya Institute of Technology for Women",
            "Sudheer Reddy College of Engineering and Technology for Women"
        ],
        "Mahbubnagar": [
            "Jayaprakash Narayan College of Engineering",
            "Sree Visvesvaraya Institute of Technology and Science"
        ],
        "Siddipet": [
            "Indur Institute of Engineering and Technology",
            "Elenki Engineering College"
        ],
        "Medak": [
            "Medak College of Engineering and Technology"
        ]
    },
    "Andhra Pradesh": {
        // ... (keeping the Andhra Pradesh data as is)
        "Markapur Rural": ["A1 Global Institute of Engineering and Technology"],
        "Gudlavalleru": ["AANM and VVRSR Polytechnic", "Gudlavalleru Engineering College"],
        "Somanapalle": ["ABR College of Engineering and Technology"],
        "Nallajerla": ["AKRG College of Engineering and Technology"],
        "Petlurivaripalem": ["AM Reddy Memorial College of Engineering and Technology"],
        "Anakapalle": ["AMAKSIK College of Technology and Management", "Rajiv Gandhi Recs Polytechnic"],
        "Guntur": [
            "ANU College of Engineering and Technology",
            "Acharya NG Ranga Agricultural University",
            "Acharya Nagarjuna University",
            "Bapatla Engineering College",
            "Chalapathi Institute of Engineering and Technology",
            "Chebrolu Engineering College",
            "Chintalapudi Engineering College",
            "College of Agricultural Engineering",
            "GVR and S College of Engineering and Technology",
            "Hindu College of Engineering and Technology",
            "KKR and KSR Institute of Technology and Sciences",
            "KLU School of Architecture",
            "Koneru Lakshmaiah Education Foundation",
            "Malineni Perumallu Educational Society's Group of Institutions",
            "NRI Institute of Technology",
            "Nalanda Institute of Engineering and Technology",
            "Newton's Institute of Science and Technology",
            "RVR and JC College of Engineering",
            "Sri Chundi Ranganayakulu Engineering College",
            "Sri Mittapalli College of Engineering",
            "Vasireddy Venkatadri Institute of Technology",
            "Vignan's Foundation for Science Technology and Research"
        ],
        "Visakhapatnam": [
            "ASK College of Technology and Management",
            "Andhra University College of Engineering",
            "Anil Neerukonda Institute of Technology and Sciences",
            "Baba Institute of Technology and Sciences",
            "Behara Polytechnic",
            "Chaitanya Engineering College",
            "Dadi Institute of Engineering and Technology",
            "Dr Lankapalli Bullayya College of Engineering for Women",
            "GITAM Institute of Technology",
            "GITAM University",
            "Gayatri Vidya Parishad College for Degree and PG Courses",
            "Gayatri Vidya Parishad College of Engineering",
            "Gayatri Vidya Parishad College of Engineering for Women",
            "Gonna Institute of Information Technology and Sciences",
            "Government Institute of Chemical Engineering",
            "Government Polytechnic",
            "Indian Institute of Petroleum and Energy Visakhapatnam",
            "Nadimpalli Satyanarayana Raju Institute of Technology",
            "Pydah College of Engineering and Technology",
            "Pydah Kaushik College of Engineering",
            "Raghu Engineering College",
            "Sai Ganapathi Engineering College",
            "Sai Ganapathi Polytechnic",
            "Sanketika Institute of Technology and Management",
            "Sanketika Polytechnic College",
            "Sanketika Vidya Parishad Engineering College",
            "Simhadhri Educational Society Group of Institutions",
            "Sri Chaitanya Engineering College",
            "Vignan's Institute of Engineering for Women",
            "Vignan's Institute of Information Technology",
            "Visakha Institute of Engineering and Technology",
            "Wellfare Institute of Science Technology and Management",
            "Yalamarty College of Polytechnic"
        ]
        // ... (rest of Andhra Pradesh data remains the same)
    }
};

export const COLLEGES = Object.values(STATES).flatMap(districts => 
    Object.values(districts).flat()
);
