
"use client";

import React from 'react';
import { useHackathon } from '@/context/HackathonProvider';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Image as ImageIcon } from 'lucide-react';
import Image from 'next/image';

export default function GeneratedImages() {
    const { state } = useHackathon();
    const { hackathons, selectedHackathonId } = state;

    const currentEvent = hackathons.find(h => h.id === selectedHackathonId);
    const imageUrl = currentEvent?.summaryImageUrl;

    return (
        <Card>
            <CardHeader>
                <CardTitle className="font-headline">Generated Summary Image</CardTitle>
                <CardDescription>A summary image of the event's statistics and spirit, generated by AI.</CardDescription>
            </CardHeader>
            <CardContent>
                {imageUrl ? (
                    <div className="relative aspect-video w-full">
                        <Image 
                            src={imageUrl} 
                            alt={`${currentEvent?.name} summary image`}
                            fill
                            className="object-contain rounded-lg"
                            unoptimized
                        />
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed rounded-lg">
                        <ImageIcon className="h-12 w-12 text-muted-foreground" />
                        <p className="mt-4 text-muted-foreground">No image has been generated for this event yet.</p>
                        <p className="text-sm text-muted-foreground">Admins or Faculty can generate one from the Project Showcase page.</p>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
