"use client";

import React from 'react';
import { useHackathon } from '@/context/HackathonProvider';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Video } from 'lucide-react';

export default function GeneratedVideos() {
    const { state } = useHackathon();
    const { hackathons, selectedHackathonId } = state;

    const currentHackathon = hackathons.find(h => h.id === selectedHackathonId);
    const videoUrl = currentHackathon?.summaryVideoUrl;

    return (
        <Card>
            <CardHeader>
                <CardTitle className="font-headline">Generated Summary Video</CardTitle>
                <CardDescription>A showcase of the hackathon's statistics and spirit, generated by AI.</CardDescription>
            </CardHeader>
            <CardContent>
                {videoUrl ? (
                    <video controls width="100%" className="rounded-lg">
                        <source src={videoUrl} type="video/webm" />
                        Your browser does not support the video tag.
                    </video>
                ) : (
                    <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed rounded-lg">
                        <Video className="h-12 w-12 text-muted-foreground" />
                        <p className="mt-4 text-muted-foreground">No video has been generated for this hackathon yet.</p>
                        <p className="text-sm text-muted-foreground">Admins or Judges can generate one from the Project Showcase page.</p>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
